# Generated by Django 4.2.7 on 2024-02-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='index/img')),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
