# Generated by Django 4.2.7 on 2024-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jinsi', models.BooleanField(max_length=50)),
                ('ismi', models.CharField(max_length=200)),
                ('yosh', models.IntegerField()),
            ],
        ),
    ]
