# Generated by Django 4.2.7 on 2024-03-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_foydalanuvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
