# Generated by Django 5.0.3 on 2024-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_about_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_af',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ar_dz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ast',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_be',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_bs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ckb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_cs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_da',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_dsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en_au',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en_gb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_eo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_es_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_es_co',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_es_mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_es_ni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_es_ve',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_et',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_eu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_fy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ga',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_gd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_gl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_he',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_hr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_hsb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_hu',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ig',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_io',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_is',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_kab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_km',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ky',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_lb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_lt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_lv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_mk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ml',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_mn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_mr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_my',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_nb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_nn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_pa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_pt_br',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_sk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_sl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_sq',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_sr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_sr_latn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_te',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_tg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_tk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_tt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_udm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ur',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_vi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_zh_hant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
